# 此处的column和结构体里的columns必须加，不然会出现反射的问题
[columns.a]
type = "enum"
data = """
[史蒂夫:1]
[大的期望:2]
[哈哈哈:3]
[千万:4]
"""
[columns.b]
type = "bitEnum"
data = """
<dfsf:1>
<上大的:2>
<xxx:3>
<aaa:77>
"""
[columns.v]
type = "text"
data = ""
[columns.k]
type = "int"
data = ""