package xstorage

import "github.com/intmian/mian_go_lib/tool/misc"

const (
	ErrSqliteDBFileAddrEmpty                   = misc.ErrStr("sqlite db file addr is empty")
	ErrSqliteDBFileAddrNotExist                = misc.ErrStr("sqlite db file addr not exist")
	ErrMgrNotInit                              = misc.ErrStr("mgr not init")
	ErrSqliteCoreNotInit                       = misc.ErrStr("sqlite core not init")
	ErrSetValue                                = misc.ErrStr("set value error")
	ErrKeyIsEmpty                              = misc.ErrStr("key is empty")
	ErrNotUseCache                             = misc.ErrStr("not use cache")
	ErrKeyNotExist                             = misc.ErrStr("key not exist")
	ErrValueIsNil                              = misc.ErrStr("value is nil")
	ErrSliceButValueIntIsNil                   = misc.ErrStr("slice but ValueInt is nil")
	ErrValueType                               = misc.ErrStr("value type error")
	ErrOpenSqlite                              = misc.ErrStr("open sqlite error")
	ErrAutoMigrate                             = misc.ErrStr("auto migrate error")
	ErrRecIsNil                                = misc.ErrStr("rec is nil")
	ErrNotUseDb                                = misc.ErrStr("not use db")
	ErrRecordToMap                             = misc.ErrStr("record to map error")
	ErrPoolType                                = misc.ErrStr("pool type error")
	ErrNotUseCacheAndNotUseDb                  = misc.ErrStr("not use cache and not use db")
	ErrGetAllValue                             = misc.ErrStr("get all value error")
	ErrGinEngineRun                            = misc.ErrStr("gin engine run error")
	ErrNotUseCacheOrNotUseDbAndFullInitLoad    = misc.ErrStr("not use cache or not use db and full init load")
	ErrUseJsonButNotUseCacheAndNotFullInitLoad = misc.ErrStr("use json, but not use cache and not full init load")
	ErrNewSqliteCore                           = misc.ErrStr("new sqlite core error")
	ErrNotUseDbAndFullInitLoad                 = misc.ErrStr("not use db and full init load")
	ErrValueUnitIsNil                          = misc.ErrStr("valueUnit is nil")
	ErrValueIsDirty                            = misc.ErrStr("value is dirty")
	ErrRemoveFromMap                           = misc.ErrStr("remove from map error")
	ErrDeleteValue                             = misc.ErrStr("delete value error")
	ErrKeyCanNotContainSquareBrackets          = misc.ErrStr("Key can not contain []")
	ErrSqliteData2Model                        = misc.ErrStr("sqliteData2Model")
	ErrCreateValue                             = misc.ErrStr("create value error")
	ErrRemoveValue                             = misc.ErrStr("remove value error")
	ErrGetSliceValue                           = misc.ErrStr("get slice value error")
	ErrsqliteModel2Data                        = misc.ErrStr("sqliteModel2Data error")
	ErrGet                                     = misc.ErrStr("get error")
)
